# ============================================================
# Transcriptomics Case Studies
# Case Study: GSE25014
#
# Lesson 01: Download Raw Microarray Data
# ============================================================
#
# Dataset:
#   GSE25014 - Gene expression data of endothelium exposed to heme
#
# Organism:
#   Homo sapiens
#
# Platform:
#   GPL570 - Affymetrix Human Genome U133 Plus 2.0 Array
#
# Samples:
#   24
#
# Experimental design:
#   2 endothelial cell types
#   2 treatment conditions
#   6 biological replicates
#
# Technology:
#   Microarray
#
# Objective:
#   Download the raw CEL files from GEO and organize the
#   metadata and probe annotation for downstream analysis.
#
# Important:
#   RMA will NOT be performed in this lesson.
#   The normalization and probe-level summarization will be
#   performed in Lesson 03.
#
# ============================================================


# ============================================================
# 1. Install packages
# ============================================================

if (!requireNamespace("BiocManager", quietly = TRUE)) {
  install.packages("BiocManager")
}

packages <- c(
  "GEOquery",
  "Biobase",
  "affy",
  "R.utils"
)

for (pkg in packages) {
  
  if (!requireNamespace(pkg, quietly = TRUE)) {
    
    BiocManager::install(
      pkg,
      ask = FALSE,
      update = FALSE
    )
  }
}


# ============================================================
# 2. Load packages
# ============================================================

library(GEOquery)
library(Biobase)
library(affy)
library(R.utils)
library(dplyr)

# ============================================================
# 3. Define project directories
# ============================================================

case_study_dir <- "GSE25014_Microarray"

if (dir.exists(case_study_dir)) {
  
  base_dir <- case_study_dir
  
} else {
  
  base_dir <- "."
}


raw_dir <- file.path(
  base_dir,
  "data",
  "raw",
  "GSE25014"
)

cel_dir <- file.path(
  raw_dir,
  "CEL"
)

metadata_dir <- file.path(
  base_dir,
  "data",
  "metadata"
)

processed_dir <- file.path(
  base_dir,
  "data",
  "processed"
)

results_dir <- file.path(
  base_dir,
  "results"
)


# Create directories

dir.create(
  cel_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  metadata_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  processed_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  results_dir,
  recursive = TRUE,
  showWarnings = FALSE
)


# ============================================================
# 4. Download raw CEL files
# ============================================================
#
# GEO provides the raw Affymetrix data as supplementary files.
#
# The CEL files contain probe-level fluorescence intensities
# generated by the microarray scanner.
#
# These files will be used in Lesson 03 to perform RMA.
# ============================================================

getGEOSuppFiles(
  "GSE25014",
  makeDirectory = FALSE,
  baseDir = raw_dir
)

# ============================================================
# 5. Identify the downloaded RAW archive
# ============================================================

raw_tar <- file.path(
  raw_dir,
  "GSE25014_RAW.tar"
)

if (!file.exists(raw_tar)) {
  
  stop(
    "GSE25014_RAW.tar was not found."
  )
}


# ============================================================
# 6. Extract CEL files
# ============================================================

untar(
  raw_tar,
  exdir = cel_dir
)


# ============================================================
# 7. Decompress CEL files
# ============================================================
#
# GEO commonly provides Affymetrix CEL files compressed
# as .CEL.gz.
#
# We decompress them so that they can be read by the affy
# package in the next lessons.
# ============================================================

cel_gz <- list.files(
  cel_dir,
  pattern = "\\.CEL\\.gz$",
  full.names = TRUE,
  ignore.case = TRUE
)

if (length(cel_gz) > 0) {
  
  for (file in cel_gz) {
    
    gunzip(
      file,
      overwrite = TRUE,
      remove = TRUE
    )
  }
}


# ============================================================
# 8. List CEL files
# ============================================================

cel_files <- list.files(
  cel_dir,
  pattern = "\\.CEL$",
  full.names = TRUE,
  ignore.case = TRUE
)

length(cel_files)

head(cel_files)


# ============================================================
# 9. Check number of samples
# ============================================================

if (length(cel_files) != 24) {
  
  warning(
    paste(
      "Expected 24 CEL files, but found",
      length(cel_files)
    )
  )
}


# ============================================================
# 10. Download GEO metadata
# ============================================================
#
# We use GEOquery to retrieve the information associated
# with the 24 samples.
#
# The expression values from the Series Matrix are NOT used
# in this pipeline.
#
# We will generate our own normalized expression matrix
# from the CEL files in Lesson 03.
# ============================================================

gse <- getGEO(
  "GSE25014",
  GSEMatrix = TRUE,
  AnnotGPL = TRUE,
  getGPL = TRUE
)


# ============================================================
# 11. Select the ExpressionSet
# ============================================================

if (is.list(gse)) {
  
  eset <- gse[[1]]
  
} else {
  
  eset <- gse
}


# ============================================================
# 12. Extract sample metadata
# ============================================================

metadata <- pData(eset) %>%
  as.data.frame()

metadata <- metadata %>%
  tibble::rownames_to_column(
    var = "SampleID"
  )


# ============================================================
# 13. Inspect metadata
# ============================================================

dim(metadata)

colnames(metadata)

head(
  metadata[, c(
    "SampleID",
    "title",
    "geo_accession"
  )]
)


# ============================================================
# 14. Extract probe annotation
# ============================================================
#
# The GPL570 annotation contains information about the
# probes present on the Affymetrix Human Genome U133 Plus 2.0
# Array.
#
# This annotation will be used in later lessons to convert
# probe-level expression into gene-level expression.
# ============================================================

annotations <- fData(eset) %>%
  as.data.frame() %>%
  tibble::rownames_to_column(
    var = "ProbeID"
  )


# ============================================================
# 15. Inspect probe annotation
# ============================================================

dim(annotations)

colnames(annotations)

head(
  annotations[, c(
    "ProbeID",
    "Gene symbol",
    "Gene title"
  )]
)


# ============================================================
# 16. Check sample information
# ============================================================

metadata %>%
  select(
    SampleID,
    title,
    starts_with("characteristics")
  ) %>%
  head(10)


# ============================================================
# 17. Save metadata
# ============================================================

write.csv(
  metadata,
  file = file.path(
    metadata_dir,
    "GSE25014_metadata.csv"
  ),
  row.names = FALSE
)


# ============================================================
# 18. Save probe annotation
# ============================================================

write.csv(
  annotations,
  file = file.path(
    metadata_dir,
    "GSE25014_probe_annotations.csv"
  ),
  row.names = FALSE
)


# ============================================================
# 19. Save ExpressionSet
# ============================================================
#
# We save the ExpressionSet mainly to preserve the GEO
# metadata and annotation retrieved during this lesson.
#
# The expression values from this object will NOT be used
# for the RMA pipeline.
# ============================================================

saveRDS(
  eset,
  file = file.path(
    raw_dir,
    "GSE25014_GEO_ExpressionSet.rds"
  )
)


# ============================================================
# 20. Create sample file list
# ============================================================

cel_info <- data.frame(
  SampleID = tools::file_path_sans_ext(
    basename(cel_files)
  ),
  CEL_file = basename(cel_files),
  stringsAsFactors = FALSE
)


print(
  cel_info
)


# ============================================================
# 21. Save CEL file list
# ============================================================

write.csv(
  cel_info,
  file = file.path(
    metadata_dir,
    "GSE25014_CEL_files.csv"
  ),
  row.names = FALSE
)


# ============================================================
# 22. Basic dataset information
# ============================================================

dim(eset)

annotation(eset)

length(cel_files)

nrow(metadata)

nrow(annotations)


# ============================================================
# 23. Final verification
# ============================================================

if (
  length(cel_files) == 24 &&
  nrow(metadata) == 24
) {
  
  print(
    "GSE25014 data successfully downloaded and organized."
  )
  
} else {
  
  print(
    "Check the downloaded files and metadata."
  )
}


# ============================================================
# 24. Files generated
# ============================================================

print(
  list.files(
    raw_dir,
    recursive = TRUE
  )
)

print(
  list.files(
    metadata_dir
  )
)


# ============================================================
# 25. Lesson complete
# ============================================================

print("Lesson 01 complete.")

print("The CEL files are ready for RMA processing in Lesson 03.")
